config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers: { confirmations: 'confirmations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
        resources :likes, only: [:create]
    end 
  end

  post '/users/:id/posts/:post_id/like', to: 'posts#like', as: 'post_like'
  namespace :api do
    resources :users, only: [] do
      resources :posts, only: [:index, :create]
      resources :posts, only: [] do
        resources :comments, only: [:index, :create], controller: 'comments'
      end
    end
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    user ||= User.new

    # Define a few sample abilities
    can :read, Post, is_publised: true

    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, counter_cache: :comments_counter

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  before_save :update_like_posts_counter

  def update_like_posts_counter
    Post.find_by(id: post_id).increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id

  scope :recent_comments, ->(post) { post.comments.order('created_at DESC').limit(5) }

  before_save :increment_posts
  after_destroy :reset_increment_posts

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :author_id, presence: true

  def comments_counter
    comments.count
  end

  # Define likes_counter method to get the count of likes

  def increment_posts
    User.find_by(id: author.id).increment!(:posts_counter)
  end

  def reset_increment_posts
    User.find_by(id: author.id).decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :set_default
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #  :confirmable

  has_many :posts, class_name: 'Post', foreign_key: 'author_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id', dependent: :destroy

  scope :recent_posts, ->(user) { user.posts.includes(:comments).order('created_at DESC').limit(3) }
  attribute :posts_counter, :integer, default: 0

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def set_default
    self.name = email.split('@')[0]
    self.posts_counter = 0
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ActionController::API
    def not_found
      render json: { error: 'not_found' }
    end

    def authorize_request
      header = request.headers['Authorization']
      header = header.split.last if header
      begin
        @decoded = JsonWebToken.decode(header)
        @user = User.find(@decoded[:user_id])
      rescue ActiveRecord::RecordNotFound => e
        render json: { errors: e.message }, status: :unauthorized
      end
    end
  end
end

app/controllers/api/comments_controller.rb
module Api
  class CommentsController < ApiController
    def index
      @user = User.find(params[:user_id])
      @post = @user.posts.find(params[:post_id])
      @comments = @post.comments
      render json: @comments
    end

    def create
      @user = User.find(params[:user_id])
      @post = @user.posts.find(params[:post_id])
      @comment = @post.comments.build(comment_params)
      @comment.user = @user

      if @comment.save
        render json: @comment, status: :created
      else
        render json: { error: 'An error occured while creating your comment!' }, status: :unprocessable_entity
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:text)
    end
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApiController
    def index
      @user = User.find(params[:user_id])
      @posts = @user.posts
      render json: @posts
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to user_post_path(current_user, @comment.post)
    else
      render :new
    end
  end

  def destroy
    authorize! :destroy, @comment

    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.find_or_create_by(author_id: current_user.id, post_id: params[:post_id])
    return unless @like.save

    redirect_to(request.referrer || root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: %i[index show]
  # , only: [:new, :create, :destroy]
  def index
    @posts = Post.includes(:comments).where(user_id: params[:id])
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    if current_user
      @post = Post.new(post_params)
      @post.author_id = current_user.id
      @post.likes_counter = 0
      @post.comments_counter = 0

      if @post.save
        redirect_to users_path
      else
        render :new
      end
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    authorize! :destroy, @post

    @post = Post.find(params[:id])
    # if current_user == @post.author
    @post = Post.find(params[:id])

    @post.likes.destroy_all
    @post.comments.destroy_all

    @post.destroy

    redirect_to root_path, notice: 'Your post was successfully deleted.'
    # else
    # end
  end

  def like
    @post = Post.find(params[:id])
    Like.create(author_id: current_user.id, post_id: @post.id)
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(posts: :comments).find(params[:id])
  end
end

app/controllers/users_controllers.rb
class UsersController < ApplicationController
    def index
    end

    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'shared/comments' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/posts/shows.html.erb
<h1>Posts Show</h1>

app/views/posts/index.html.erb
<%= render 'shared/users', user: @user %>

<% @posts.each  do  |post|%>
<div class="boxes comments-container">
    <a href="/users/<%= post.author_id%>/posts/<%= post.id %>"><%= post.title%></a>
        <p><%= post.text%></p>
        <p class="likes-comments">
            Comments: <%= post.comments_counter %> Likes: <%= post.likes_counter%>
        </p>
</div>

<div class="boxes">
<% Post.recent_comments(post).each  do |comment|%>
    <p><%= comment.author.name%> - <%= comment.text %></p>
    <%end%>
</div>
<br />
<%end%>

<div class="smaller-buttons">
  Pagination
</div>

app/views/posts/new.html.erb
<div class="all-forms">
<h1>New Post</h1>
<% if @post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>

<% end%>
<%= form_with url: user_posts_path, model: @post do |form|%>
<%= form.label :title %>
<%= form.text_field :title%>
<br/>
<%= form.label :text %>
<%= form.text_field :text%>
<br/>

<%= form.submit %>

<%end%>
</div>

app/views/posts/show.html.erb
<div class="show-posts-container">
  <div class="boxes">
    <div class="posts-content">
      <h1><%= @post.title%> by <%= @post.author.name%></h1>
      <p>
        Comments: <%= @post.comments_counter%> 
        Likes: <%= @post.likes_counter %>
      </p>
    </div>

    <p> <%= @post.text%></p>
  </div>

  <%= render 'shared/like', model: @like, url: post_like_path(@post, :post_id) %>
    <div class="smaller-buttons">
      <a class="comment-button" href=<%="/users/user_id/posts/#{@post.id}/comments/new"%>>Comment</a>
    </div>

  <div class="boxes posts-messages">
    <% @post.comments.each do |comment| %>
     <p><%= comment.author.name%>: <%= comment.text %></p>
      <div class="smaller-buttons">
        <% if can? :destroy, comment %>
          <%= form_with(model: @comment, url: user_post_comment_path(params[:user_id], @post, comment), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'delete_post') do |form| %>
            <%= form.submit "Delete comment", class:"inner-buttons"%>
          <% end %>
        <% end %>
      </div>
    <%end%>
  </div>
  
  <div class="smaller-buttons">
    <% if can? :destroy, @post %>
      <%= form_with(model: @post, url: user_post_path(params[:user_id], @post), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'delete_post') do |form| %>
        <%= form.submit "Delete Post", class:"inner-buttons"%>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_comments.html.erb
<%= form_with model: @comment, url: user_post_comments_path do |form|%>

<%= form.label :text, 'Add Comment' %>

<%= form.text_field :text%>
<br/>
<div class="smaller-buttons">
    <%= form.submit%>
</div>
<% end %>

app/views/shared/_like.html.erb
<%= form_with model: model, url: url, local: true do |form| %>
  <%= form.submit "Like", id:"ïnner-button"%>
<% end %>

app/views/shared/_users.html.erb
<div id="each-user">
    <div class="boxes img-card">
      <img src=<%= user.photo %> alt="profile" class="img-card">
    </div>
    <div class=" boxes user-card" >
      <a href="/users/<%= user.id%>"> <h2 class="user-name"> <%= user.name %></h2></a>
      <p class="post-counter">Number of posts: <%= user.posts_counter%> </p>
    </div>
 
</div>

app/views/shared/likes.html.erb
<%= form_with model: @like , url: "/users/#{params[:user_id]}/posts/#{params[:post_id]}/likes/create" do |form| %>
<%= form.submit "Like" %>
<% end %>

app/views/users/index.html.erb
<div>
    <a href="/users/new/posts/new"> New Post</a>
</div>
<% @users.each do |user| %>

    <%= render 'shared/users', user: user %>
    
<% end %>

app/views/users/show.html.erb
<%= render 'shared/users', user: @user %>

<article id="bio-container">
<div class="boxes">
    <h1>Bio</h1>
        <p><%= @user.bio %></p>
</div>
<% User.recent_posts(@user).each do |post| %>
    <div class="boxes">
    <h1>
      <a href="/users/<%= post.author_id%>/posts/<%= post.id %>">
      <%= post.title %></a>
    </h1>
        <p><%= post.text %></p>
        <p class="likes-comments">Comments: <%= post.comments_counter %> Likes: <%= post.likes_counter %></p>
    </div>
<%end%>
    
<div class="smaller-buttons">
  <a href="/users/<%= @user.id%>/posts">See all Posts</a>
</div>
</article>

app/views/users/shows.html.erb
<h1>Users Show </h1>